### ISSUE TITLE
rm top level code from test files

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#155]
see for instance https://github.com/maelle/swamp

**Comment by dpprdan** [comment]
Ha, I thought about this last weekend as well. 😆 
But more in the [test-fixtures](https://testthat.r-lib.org/articles/test-fixtures.html) sense, i.e. should the objects be removed afterwards. I came to the conclusion that because these are "only" data.frames (i.e. objects in the global env) and not side effects (which is the focus of the text-fixtures article) that it's not a problem if they aren't removed.

**Comment by maelle** [comment]
why not make these objects functions and call it in each test to create the object? even if the current behavior in the PR is fine, having them as functions would seem tidier to me. :thinking:
