### ISSUE TITLE
no results with `limit=1` and `min_confidence=7`

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#161]
@freyfogle I think I found an edge case bug again.

The following doesn't return a result for me:
https://api.opencagedata.com/geocode/v1/json?q=Brest&limit=1&min_confidence=7&key=OPENCAGE_KEY

While increasing the `limit` does return several results:

https://api.opencagedata.com/geocode/v1/json?q=Brest&limit=10&min_confidence=7&key=OPENCAGE_KEY

**Comment by dpprdan** [comment]
In addition I get a different number of results if I add `language` into the mix. 

E.g. 4 result sets with `language=de` (similarly with `language=fr` or `language=native`)

https://api.opencagedata.com/geocode/v1/json?q=Brest&limit=10&min_confidence=7&language=de&key=OPENCAGE_KEY

and 7 result sets with `language=en`:

https://api.opencagedata.com/geocode/v1/json?q=Brest&limit=10&min_confidence=7&language=en&key=OPENCAGE_KEY

**Comment by dpprdan** [comment]
This isn't limited to Brest @freyfogle, c.f.
https://api.opencagedata.com/geocode/v1/json?q=Orléans&limit=1&min_confidence=7&key=OPENCAGE_KEY
https://api.opencagedata.com/geocode/v1/json?q=Orléans&limit=10&min_confidence=7&key=OPENCAGE_KEY

**Comment by freyfogle** [comment]
Hi, sorry, I have been sick this week. Will have a look over Christmas, but fundamentally this is because 

For  speed, when the limit is low (for example `limit=1`) we only query the various backend geocoders for a few results and then we apply the fllter (in this case `min_confidence`).  It may be that none of the results match the filter. When the limit is high (`limit=10`) we query for more results and then apply the filter. To a degree this is just the distributed nature of our service. To be honest we have considered dropping`min_confidence` as a supported filter entirely, as confidence is so misunderstood (our own fault, it is badly named).

Anyway, I think a part of the confusion here is the (false) assumption that we are querying one big SQL database and adding WHERE clauses and such. That is not the case at all, we have so many different datasources (depending on the query). They all get queried and then we put the result set together. 

All that said, the language issue does surprise me, will investigate over the xmas break.

**Comment by dpprdan** [comment]
I understand all that. Still, getting no results when there in fact _are_ results available is confusing from a user's perspective, isn't it?

Best wishes for a speedy recovery!

**Comment by freyfogle** [comment]
Life can sometimes be confusing.

The reality is (based on actual data) almost no one uses deep filters like this. Should we make everyone's request slower to make it less confusing for 0.001% of the users?

**Comment by dpprdan** [comment]
Well, it certainly would help with my tests! 😉

**Comment by freyfogle** [comment]
yes, i do understand

but just because you have a test doesn't mean that is actually bow users use the service. 

Nevertheless over the holiday break I will see what we can do here. 

Frohe Weihnachten!

**Comment by dpprdan** [comment]
Dir auch frohe Weihnachten! 🎄

**Comment by freyfogle** [comment]
Actually I was just looking into this and FYI we removed the documentation for `min_confidence` years ago

See the list of supported optional params
https://opencagedata.com/api#optional-params

apologies for my confusion.

**Comment by dpprdan** [comment]
Haha, then we should drop `min_confidence` from this package as well.
