### ISSUE TITLE
activate lintr tests

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#33]
See https://github.com/ropensci/opencage/pull/29#issuecomment-365164035

@maelle I said I would check, but don't really know where...

**Comment by maelle** [comment]
Ok will do!

**Comment by dpprdan** [comment]
LOL, that was easy! Really don't know how I missed the `#` in test-lintr.R

**Comment by maelle** [comment]
Well _activating_ the test was indeed easy but getting it to pass less so, I forgot to mention this issue in the previous commit where I added many line returns because the docs lines were too long and got flagged. This is what motivated me to remove docs duplicates because I didn't want to have to correct everything twice. :joy:
