### ISSUE TITLE
add documentation for oc_forward and oc_reverse

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#34]

**Comment by jessesadler** [comment]
I am a little unclear what the overall design goals are for `oc_forward` and `oc_reverse`. Right now they output a list of lists, which if we want to be able to have a data frame output, has to go through a fair amount of parsing. This also brings up the issue of where and how we want to vectorize the request and response. My implementation in PR #31 is to have the request be made, the result received, and have an initial data frame be created and then vectorize this process as a whole rather than in chunks. @dpprdan and @maelle I would be happy to hear your thoughts on the more general design. I have not tried to pull in my own pull request, because I do not want to interfere with general goals of the project, plus the functions I created have dumb names. 😜

**Comment by dpprdan** [comment]
fixed in devel, but see #71
