### ISSUE TITLE
Vignette(s) topics

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#53]
A list of topics/new features to address in vignette(s) / news:

- [x] output options
  - [x] df_list
  - [x] json_list
  - [x] url_only #35 
- [x] ratelimit #32

**Comment by maelle** [comment]
Now I wonder about how to split these topics efficiently into several articles / vignettes (assuming I'll run `pkgdown::build_site()` 😺 ).

One about basic use (showing the different output options but especially the first two), and then should the advanced topics like

* debugging (url_only)

* rate limit

* getting more out of the API (i.e. more columns) & wrangling that with `jqr`/something else

* geojson etc

be grouped? maybe each on their own makes sense actually. 🤔

**Comment by maelle** [comment]
Really explain well that by default with the df functions one gets 1 result per address, which result that is (highest confidence? pointing to the API docs), and how to change that.

**Comment by freyfogle** [comment]
Hi. Confidence is NOT a measure of correctness. It is NOT the best answer to the query. The best answer is the first result. 

As an example, a search for "London". The first result is London, UK, with a confidence of 1 (because London is big). The second result is London, Ontario, Canada with confidence of 4, because it is less big. 

Please see https://geocoder.opencagedata.com/api#confidence

**Comment by maelle** [comment]
Aaaah see I'd be the first to need that vignette in the R package 😀 thanks!

**Comment by maelle** [comment]
Another point to have in vignettes, a sentence about the fact the functions are vectorized but it does _not_ mean things are sent in bulk to the API.

**Comment by dpprdan** [comment]
another detail: [FIPS codes](https://blog.opencagedata.com/post/new-annotation-fips)

**Comment by dpprdan** [comment]
Closed with #114
