### ISSUE TITLE
Before a PR asking questions here

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#61]
From looking at your fantastic work in https://github.com/ropensci/opencage/compare/master...dpprdan:feat_pmap @dpprdan I'll update it if I have more questions.

* Reg `oc_url` why use  `is_testing` rather than mocking in tests? And can you confirm the key isn't shown on any CI log?

**Comment by maelle** [comment]
* Could you update NEWS.md? Going forward (:wink: ) I suggest we use http://style.tidyverse.org/news.html

**Comment by maelle** [comment]
And once you've updated NEWS.md I'd suggest opening a PR even if not ready for merging, so that we can see the CI/coverage results.

**Comment by dpprdan** [comment]
Re: `oc_url` and `is_testing`: well spotted! My initial idea was that it would be save to test whether `oc_process()` would create valid URLs as long as I provide a fake key in the test file. What I did not really think about is that by allowing URLs to be shown in tests, it IS possible that a key is shown in the CI logs (TBH I did not think about CI logs at all) if one is not careful to not provide a valid key when testing `oc_process()` (or `oc_forward()`/`oc_reverse()`). Especially since `oc_key()` is the default option for the `key` parameter. So not such a good idea after all. 😧 

In general I thought (and still think) that it is possible to safely test URLs without mocking (assuming you mean via `webmockr` & `vcr`), because this happens completely on the R side (i.e. before an API call) and is basically just a string comparison. 

So I made some [changes](https://github.com/dpprdan/opencage/compare/feat_pmap...dpprdan:fix_safer_url_tests) to make sure the URL is only shown when the session is `interactive()` or when the `key` is `NULL`. I think this ought to be safe now. What do you think?

**Comment by maelle** [comment]
yes it seems safer, thank you, and it's quite unlikely anyone would need the URL outside of interactive use?

**Comment by dpprdan** [comment]
I cannot think of any reasonable use-case ATM. But if there is one, it is still possible to add (i.e. paste) the API key to the URL afterwards.

**Comment by maelle** [comment]
then it's all perfect :-)
